export const NEW_EMPLOYEE = 'NEW_EMPLOYEE';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const SET_DEPARTMENT_FILTER = 'SET_DEPARTMENT_FILTER';
export const REMOVE_DEPARTMENT_FILTER = 'REMOVE_DEPARTMENT_FILTER';
export const CHANGE_MENU_SELECTION = 'CHANGE_MENU_SELECTION';
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';
export const ADD_NEW_IDENTITY = 'ADD_NEW_IDENTITY';
export const NEW_ORGANIZATION_ADDED = 'NEW_ORGANIZATION_ADDED';



